version: '3.8'

services:
  app:
    build: .
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_DATABASE_URL=mysql+pymysql://p_titan_corp:IQpN92rcdZy5yig1@localhost:3306/p_titan_corp
    volumes:
      - .:/app
    restart: unless-stopped
